---
version: '3.7'

services:
  weather_exporter:
    container_name: weather_exporter
    hostname: weather_exporter
    image: weather_exporter
    build:
      context: ./
    restart: always
    command: "web --listen '0.0.0.0:8080' --app-id '6f2bbbdbb606f96a81a30961e8cc0d61' 'Tokyo,JP' 'Saitama,JP' 'Kyoto,JP' 'Osaka,JP'"
    expose:
      - '8080'
    networks:
      - planet-link
    logging:
      driver: "json-file"
      options:
        max-file: '4'
        max-size: '250m'
networks:
  planet-link:
    external:
      name: planet-link

