name: Publish Docker image

on:
  push:
    branches-ignore:
      - dependabot/**
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-buildx-action@v1
        with:
          driver: docker
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v1.1.1
        id: docker_build
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}
          repository: ${{ github.repository_owner }}/weather_exporter
          tag_with_ref: true
          tag_with_sha: true
          tags: latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
